---
# file: roles/role-solr/tasks/solr_debian.yml

- name: Grab Solr
  get_url: url={{solr_source}}/{{solr_version}}/solr-{{solr_version}}.tgz dest={{solr_destination}}

- name: Extract Solr
  command: tar xzvf {{solr_destination}}/solr-{{solr_version}}.tgz -C {{solr_destination}}

- name: Create symlink to solr
  file: state=link src={{solr_destination}}/solr-{{solr_version}} dest={{solr_destination}}/solr

- name: Set up solr_home directory and core
  file: state=directory path={{solr_home}}/{{solr_core_name}}/conf

- name: solr.xml
  template: > 
    src=solr_xml.j2 dest={{solr_home}}/solr.xml

- name: core.properties
  template: > 
    src=core_properties.j2 dest={{solr_home}}/{{solr_core_name}}/core.properties

- name: solrconfig.xml
  template: > 
    src=solrconfig_xml.j2 dest={{solr_home}}/{{solr_core_name}}/conf/solrconfig.xml
  
- name: schema.xml
  template: > 
    src=schema_xml.j2 dest={{solr_home}}/{{solr_core_name}}/conf/schema.xml  

- name: Startup script
  template: > 
    src=solr.j2 dest=/etc/init.d/solr
    owner=root group=root mode=755